// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgreeToTerms(arg1) {
  return window['go']['main']['App']['AgreeToTerms'](arg1);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CheckFirstRun() {
  return window['go']['main']['App']['CheckFirstRun']();
}

export function CheckInstallConflicts(arg1, arg2) {
  return window['go']['main']['App']['CheckInstallConflicts'](arg1, arg2);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DeleteMod(arg1) {
  return window['go']['main']['App']['DeleteMod'](arg1);
}

export function GetThemeList() {
  return window['go']['main']['App']['GetThemeList']();
}

export function GetVoiceList() {
  return window['go']['main']['App']['GetVoiceList']();
}

export function ImportSelectedZip(arg1) {
  return window['go']['main']['App']['ImportSelectedZip'](arg1);
}

export function ImportZips(arg1, arg2) {
  return window['go']['main']['App']['ImportZips'](arg1, arg2);
}

export function ImportZipsFromPending(arg1) {
  return window['go']['main']['App']['ImportZipsFromPending'](arg1);
}

export function InitAppState() {
  return window['go']['main']['App']['InitAppState']();
}

export function InstallMod(arg1, arg2) {
  return window['go']['main']['App']['InstallMod'](arg1, arg2);
}

export function LoadThemeContent(arg1) {
  return window['go']['main']['App']['LoadThemeContent'](arg1);
}

export function MinimizeApp() {
  return window['go']['main']['App']['MinimizeApp']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RestoreGame() {
  return window['go']['main']['App']['RestoreGame']();
}

export function SaveThemeSelection(arg1) {
  return window['go']['main']['App']['SaveThemeSelection'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartAutoSearch() {
  return window['go']['main']['App']['StartAutoSearch']();
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}
