// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgreeToTerms(arg1:string):Promise<void>;

export function BrowseFolder():Promise<Record<string, any>>;

export function CheckFirstRun():Promise<Record<string, any>>;

export function CheckInstallConflicts(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ClearLogs():Promise<void>;

export function CloseApp():Promise<void>;

export function DeleteMod(arg1:string):Promise<boolean>;

export function GetThemeList():Promise<Array<main.ThemeMeta>>;

export function GetVoiceList():Promise<Array<Record<string, any>>>;

export function ImportSelectedZip(arg1:string):Promise<void>;

export function ImportZips(arg1:Array<string>,arg2:string):Promise<void>;

export function ImportZipsFromPending(arg1:string):Promise<void>;

export function InitAppState():Promise<Record<string, any>>;

export function InstallMod(arg1:string,arg2:string):Promise<void>;

export function LoadThemeContent(arg1:string):Promise<Record<string, any>>;

export function MinimizeApp():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RestoreGame():Promise<void>;

export function SaveThemeSelection(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartAutoSearch():Promise<void>;

export function ToggleMaximise():Promise<void>;

export function TogglePin(arg1:boolean):Promise<void>;
